name: watermarker
description: "A tool to watermark images"
publish_to: 'none' 

version: 0.0.2+2

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.6
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  image: ^4.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  slang: ^4.1.0
  slang_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  lint: ^2.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^4.1.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
